language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.mvn'

script: "./mvnw clean install"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - heemanghan@gmail.com